// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqDLCxu_g_1RpU7VRDymSg3EoJrwCkcgg',
    appId: '1:831862827644:web:cfb80d5024efafb12677f9',
    messagingSenderId: '831862827644',
    projectId: 'library-app-6688b',
    authDomain: 'library-app-6688b.firebaseapp.com',
    storageBucket: 'library-app-6688b.appspot.com',
    measurementId: 'G-9LCJJ244WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4NL1D4295M8ZrAvWs-acAAv35mEJLNw',
    appId: '1:831862827644:android:17d0466c50bc52bf2677f9',
    messagingSenderId: '831862827644',
    projectId: 'library-app-6688b',
    storageBucket: 'library-app-6688b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhXttSl2ZAfeLCkAZLVdOTX2s__IExqf8',
    appId: '1:831862827644:ios:9259ee09425150f52677f9',
    messagingSenderId: '831862827644',
    projectId: 'library-app-6688b',
    storageBucket: 'library-app-6688b.appspot.com',
    iosBundleId: 'com.mauricejyaheza.libraryFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhXttSl2ZAfeLCkAZLVdOTX2s__IExqf8',
    appId: '1:831862827644:ios:a4510ebbddfd63f32677f9',
    messagingSenderId: '831862827644',
    projectId: 'library-app-6688b',
    storageBucket: 'library-app-6688b.appspot.com',
    iosBundleId: 'com.mauricejyaheza.libraryFlutterApp.RunnerTests',
  );
}
