name: Deploy Flutter Web App to Firebase Hosting

"on":
  push:
    branches:
      - main # Adjust this to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web # Adjust this for iOS or Android builds

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
